"""SCAD and STL generation orchestration."""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path

from selflensbahtinov.models import GenerationOptions, LensProfile
from selflensbahtinov.validation import load_profile

LOGGER = logging.getLogger(__name__)
REPO_ROOT = Path(__file__).resolve().parents[2]
TEMPLATE_PATH = REPO_ROOT / "openscad" / "lens_mask.scad"


def scad_include_path(path: Path) -> str:
    """Return a path formatted for OpenSCAD include/use statements."""
    return path.resolve().as_posix()


def render_scad(profile: LensProfile, template_path: Path = TEMPLATE_PATH, *, test_ring: bool = False, engrave_label: bool = True) -> str:
    """Render a small OpenSCAD entrypoint configured for a profile."""
    inner_diameter = profile.inner_diameter_mm
    outer_diameter = inner_diameter + 10.0
    label = profile.label.replace('"', "'")
    return "\n".join(
        [
            "// Generated by SelfLensBahtinov. Edit the JSON profile, not this file.",
            f'use <{scad_include_path(template_path)}>',
            f"inner_diameter_mm = {inner_diameter:.3f};",
            f"outer_diameter_mm = {outer_diameter:.3f};",
            f"mask_thickness_mm = {profile.mask_thickness_mm:.3f};",
            f"ring_depth_mm = {profile.ring_depth_mm:.3f};",
            f"fit_clearance_mm = {profile.fit_clearance_mm:.3f};",
            f'label_text = "{label}";',
            f"engrave_label = {str(engrave_label).lower()};",
            f"test_ring_mode = {str(test_ring).lower()};",
            "lens_mask(",
            "    inner_diameter_mm = inner_diameter_mm,",
            "    outer_diameter_mm = outer_diameter_mm,",
            "    mask_thickness_mm = mask_thickness_mm,",
            "    ring_depth_mm = ring_depth_mm,",
            "    label_text = label_text,",
            "    engrave_label = engrave_label,",
            "    test_ring_mode = test_ring_mode",
            ");",
            "",
        ]
    )


def generate_scad(options: GenerationOptions) -> Path:
    """Generate a configured SCAD file from a profile."""
    profile = load_profile(options.profile_path)
    content = render_scad(profile, test_ring=options.test_ring, engrave_label=options.engrave_label)
    LOGGER.info("Generating SCAD for %s at %s", profile.slug, options.output_path)
    if options.dry_run:
        LOGGER.info("Dry run: would write %s", options.output_path)
        return options.output_path
    options.output_path.parent.mkdir(parents=True, exist_ok=True)
    options.output_path.write_text(content, encoding="utf-8")
    return options.output_path


def generate_stl(options: GenerationOptions) -> Path:
    """Generate an STL file by rendering SCAD and invoking OpenSCAD."""
    scad_path = options.output_path.with_suffix(".scad")
    scad_options = GenerationOptions(
        profile_path=options.profile_path,
        output_path=scad_path,
        test_ring=options.test_ring,
        engrave_label=options.engrave_label,
        dry_run=options.dry_run,
        openscad_executable=options.openscad_executable,
    )
    generate_scad(scad_options)
    command = [options.openscad_executable, "-o", str(options.output_path), str(scad_path)]
    LOGGER.info("Running OpenSCAD: %s", " ".join(command))
    if options.dry_run:
        LOGGER.info("Dry run: would run OpenSCAD and write %s", options.output_path)
        return options.output_path
    options.output_path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(command, check=True)
    return options.output_path
