"""OpenSCAD rendering for already-calculated V1 mask geometry."""

from __future__ import annotations

import json
from abc import ABC, abstractmethod

from selflensbahtinov.models import MaskGeometry

_EPSILON = 0.02


class MaskRenderer(ABC):
    @abstractmethod
    def render_scad(self, geometry: MaskGeometry) -> str:
        """Render geometry as readable SCAD."""


def _scad_string(value: str) -> str:
    return json.dumps(value)


class OpenScadRenderer(MaskRenderer):
    def _mounting_module(self, g: MaskGeometry) -> list[str]:
        pts = ", ".join(f"[{p.radius_mm:.4f}, {p.z_mm:.4f}]" for p in g.ring.cross_section)
        return [
            f"// mount_diameter_mm={g.ring.mount_diameter_mm:.4f} clearance_mm={g.ring.clearance_mm:.4f} inner_fit_diameter_mm={g.ring.inner_diameter_mm:.4f}",
            f"// ring_depth_mm={g.ring.depth_mm:.4f} lead_in_chamfer_mm={g.ring.lead_in_chamfer_mm:.4f} outer_edge_radius_mm={g.ring.outer_edge_radius_mm:.4f} straight_engagement_mm={g.ring.straight_engagement_mm:.4f}",
            f"// mounting_entry_side={g.ring.mounting_entry_side}; print with mounting ring on build plate, negative-Z entry side down, no supports.",
            "module mounting_ring() {",
            f"  rotate_extrude(convexity=4) polygon(points=[{pts}]);",
            "}",
        ]

    def render_scad(self, geometry: MaskGeometry) -> str:
        if geometry.test_ring:
            return self._render_test_ring(geometry)
        return self._render_full_mask(geometry)

    def _common_modules(self, geometry: MaskGeometry) -> list[str]:
        radius = geometry.clear_aperture_mm / 2
        return [
            "$fn = 128;",
            f"epsilon = {_EPSILON:.3f};",
            "module slot_rectangle(cx, cy, len, wid, angle) {",
            "  translate([cx, cy, mask_thickness_mm / 2]) rotate([0, 0, angle]) cube([len, wid, mask_thickness_mm + 2 * epsilon], center=true);",
            "}",
            "module aperture_clip() {",
            f"  translate([0, 0, -epsilon]) cylinder(h=mask_thickness_mm + 2 * epsilon, d={geometry.clear_aperture_mm:.4f});",
            "}",
            f"region_gap_mm = {geometry.region_gap_mm:.4f};",
            "module region_clip(region) {",
            f"  r = {radius + geometry.slot_spacing_mm * 2:.4f};",
            "  g = region_gap_mm / 2;",
            "  points = region == \"left-reference\" ? [[-r, -r], [-g, -r], [-g, r], [-r, r]] :",
            "    region == \"right-upper\" ? [[g, g], [r, g], [r, r], [g, r]] :",
            "    region == \"right-lower\" ? [[g, -g], [r, -g], [r, -r], [g, -r]] :",
            "    region == \"tribahtinov-0\" ? concat([[0, 0]], [for (i = [0:8]) [r * cos(-60 + 60 * i / 8), r * sin(-60 + 60 * i / 8)]]) :",
            "    region == \"tribahtinov-1\" ? concat([[0, 0]], [for (i = [0:8]) [r * cos(0 + 60 * i / 8), r * sin(0 + 60 * i / 8)]]) :",
            "    region == \"tribahtinov-2\" ? concat([[0, 0]], [for (i = [0:8]) [r * cos(60 + 60 * i / 8), r * sin(60 + 60 * i / 8)]]) :",
            "    region == \"tribahtinov-3\" ? concat([[0, 0]], [for (i = [0:8]) [r * cos(120 + 60 * i / 8), r * sin(120 + 60 * i / 8)]]) :",
            "    region == \"tribahtinov-4\" ? concat([[0, 0]], [for (i = [0:8]) [r * cos(180 + 60 * i / 8), r * sin(180 + 60 * i / 8)]]) :",
            "    concat([[0, 0]], [for (i = [0:8]) [r * cos(240 + 60 * i / 8), r * sin(240 + 60 * i / 8)]]);",
            "  translate([0, 0, -epsilon]) linear_extrude(height=mask_thickness_mm + 2 * epsilon) polygon(points);",
            "}",
            "module clipped_slot(cx, cy, len, wid, angle, region) {",
            "  intersection() {",
            "    slot_rectangle(cx, cy, len, wid, angle);",
            "    aperture_clip();",
            "    region_clip(region);",
            "  }",
            "}",
        ]

    def _render_full_mask(self, g: MaskGeometry) -> str:
        lines = [
            "// Generated by SelfLensBahtinov V1. Python calculated all mask geometry.",
            f"// profile={g.profile_slug} mask={g.mask_type.value} clear_aperture_mm={g.clear_aperture_mm:.3f} pattern_border_mm={g.pattern_border_mm:.3f}",
            f"mask_thickness_mm = {g.thickness_mm:.4f};",
            *self._common_modules(g),
            *self._mounting_module(g),
            "difference() {",
            "  union() {",
            "    // Solid front face. Do not subtract a circular clear-aperture hole.",
            f"    cylinder(h=mask_thickness_mm, d={g.ring.outer_diameter_mm:.4f});",
            "    // Shared Python cross-section mounting skirt: lead-in chamfer and external edge treatment.",
            "    mounting_ring();",
            "  }",
        ]
        for slot in g.slots:
            lines.append(
                f'  clipped_slot({slot.center.x:.4f}, {slot.center.y:.4f}, {slot.length_mm:.4f}, {slot.width_mm:.4f}, {slot.angle_deg:.3f}, "{slot.region.value}");'
            )
        if g.label:
            lines.extend(
                [
                    "  // Label is placed in peripheral material outside the clear aperture.",
                    f'  translate([{g.label.position.x:.4f}, {g.label.position.y:.4f}, {g.thickness_mm - 0.35:.4f}]) linear_extrude(height=0.4) text({_scad_string(g.label.text)}, size={g.label.size_mm:.4f}, halign="center", valign="center");',
                ]
            )
        lines.extend(["}", ""])
        return "\n".join(lines)

    def _render_test_ring(self, g: MaskGeometry) -> str:
        return "\n".join(
            [
                "// Generated by SelfLensBahtinov V1 fit-test ring.",
                "$fn = 128;",
                f"epsilon = {_EPSILON:.3f};",
                f"// test_ring_depth_mm={g.ring.depth_mm:.3f}",
                *self._mounting_module(g),
                "mounting_ring();",
                "",
            ]
        )
