"""OpenSCAD rendering for already-calculated V1 mask geometry."""

from __future__ import annotations

import json
from abc import ABC, abstractmethod

from selflensbahtinov.models import MaskGeometry

_EPSILON = 0.02


class MaskRenderer(ABC):
    @abstractmethod
    def render_scad(self, geometry: MaskGeometry) -> str:
        """Render geometry as readable SCAD."""


def _scad_string(value: str) -> str:
    return json.dumps(value)


class OpenScadRenderer(MaskRenderer):
    def render_scad(self, geometry: MaskGeometry) -> str:
        if geometry.test_ring:
            return self._render_test_ring(geometry)
        return self._render_full_mask(geometry)

    def _common_modules(self, geometry: MaskGeometry) -> list[str]:
        radius = geometry.clear_aperture_mm / 2
        return [
            "$fn = 128;",
            f"epsilon = {_EPSILON:.3f};",
            "module slot_rectangle(cx, cy, len, wid, angle) {",
            "  translate([cx, cy, mask_thickness_mm / 2]) rotate([0, 0, angle]) cube([len, wid, mask_thickness_mm + 2 * epsilon], center=true);",
            "}",
            "module aperture_clip() {",
            f"  translate([0, 0, -epsilon]) cylinder(h=mask_thickness_mm + 2 * epsilon, d={geometry.clear_aperture_mm:.4f});",
            "}",
            "module sector_clip(start_deg, end_deg) {",
            f"  r = {radius + geometry.slot_spacing_mm * 2:.4f};",
            "  step = max(2, ceil(abs(end_deg - start_deg) / 8));",
            "  points = concat([[0, 0]], [for (i = [0:step]) [r * cos(start_deg + (end_deg - start_deg) * i / step), r * sin(start_deg + (end_deg - start_deg) * i / step)]]);",
            "  translate([0, 0, -epsilon]) linear_extrude(height=mask_thickness_mm + 2 * epsilon) polygon(points);",
            "}",
            "module clipped_slot(cx, cy, len, wid, angle, start_deg, end_deg) {",
            "  intersection() {",
            "    slot_rectangle(cx, cy, len, wid, angle);",
            "    aperture_clip();",
            "    sector_clip(start_deg, end_deg);",
            "  }",
            "}",
        ]

    def _render_full_mask(self, g: MaskGeometry) -> str:
        lines = [
            "// Generated by SelfLensBahtinov V1. Python calculated all mask geometry.",
            f"// profile={g.profile_slug} mask={g.mask_type.value} clear_aperture_mm={g.clear_aperture_mm:.3f} pattern_border_mm={g.pattern_border_mm:.3f}",
            f"mask_thickness_mm = {g.thickness_mm:.4f};",
            *self._common_modules(g),
            "difference() {",
            "  union() {",
            "    // Solid front face. Do not subtract a circular clear-aperture hole.",
            f"    cylinder(h=mask_thickness_mm, d={g.ring.outer_diameter_mm:.4f});",
            "    // Hollow mounting skirt behind the front face.",
            f"    translate([0, 0, -{g.ring.depth_mm:.4f}]) difference() {{",
            f"      cylinder(h={g.ring.depth_mm:.4f}, d={g.ring.outer_diameter_mm:.4f});",
            f"      translate([0, 0, -epsilon]) cylinder(h={g.ring.depth_mm:.4f} + epsilon, d={g.ring.inner_diameter_mm:.4f});",
            "    }",
            "  }",
        ]
        for slot in g.slots:
            lines.append(
                f"  clipped_slot({slot.center.x:.4f}, {slot.center.y:.4f}, {slot.length_mm:.4f}, {slot.width_mm:.4f}, {slot.angle_deg:.3f}, {slot.sector_start_deg:.3f}, {slot.sector_end_deg:.3f});"
            )
        if g.label:
            lines.extend(
                [
                    "  // Label is placed in peripheral material outside the clear aperture.",
                    f'  translate([{g.label.position.x:.4f}, {g.label.position.y:.4f}, {g.thickness_mm - 0.35:.4f}]) linear_extrude(height=0.4) text({_scad_string(g.label.text)}, size={g.label.size_mm:.4f}, halign="center", valign="center");',
                ]
            )
        lines.extend(["}", ""])
        return "\n".join(lines)

    def _render_test_ring(self, g: MaskGeometry) -> str:
        return "\n".join(
            [
                "// Generated by SelfLensBahtinov V1 fit-test ring.",
                "$fn = 128;",
                f"epsilon = {_EPSILON:.3f};",
                f"// test_ring_depth_mm={g.ring.depth_mm:.3f}",
                "difference() {",
                f"  translate([0, 0, -{g.ring.depth_mm:.4f}]) cylinder(h={g.ring.depth_mm:.4f}, d={g.ring.outer_diameter_mm:.4f});",
                f"  translate([0, 0, -{g.ring.depth_mm:.4f} - epsilon]) cylinder(h={g.ring.depth_mm:.4f} + 2 * epsilon, d={g.ring.inner_diameter_mm:.4f});",
                "}",
                "",
            ]
        )
